version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: certchain-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: CertChain_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CertChain_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - certchain-network

volumes:
  postgres_data:

networks:
  certchain-network:
    driver: bridge
